#!/usr/bin/perl -w
#
# Copyright (C) 2007 Markus Hesse
# Copyright (C) 2009 Foswiki Contributors
#
# For licensing info read LICENSE file in the Foswiki root.
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details, published at 
# http://www.gnu.org/copyleft/gpl.html

# Set library paths in @INC, at compile time
BEGIN {
    unshift @INC, '.';
    unshift @INC, '../bin'; # SMELL: argh where's the foswiki installation
    require 'setlib.cfg';
    require 'LocalSite.cfg';
}

use Foswiki;
use Foswiki::Contrib::KinoSearchContrib::Index;
use strict;

my $debug = ! ( @ARGV && $ARGV[0] eq "-q" );

$debug && print "KinoSearch index files init\n";
$debug && print "- to suppress all normal output: kinoindex -q\n";

my $foswiki = new Foswiki();

my $indexer = Foswiki::Contrib::KinoSearchContrib::Index->newCreateIndex();
$indexer->createIndex($debug)

# EOF
